name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v4
      - name: Release
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
        with:
          version: "v0.16.3"
          verb: call 
          module: github.com/MartinSimango/daggerverse/gopkg@v0.3.0 
          args: "with-git-gpg-config --gpg-key=env://GPG_KEY --gpg-key-id=env://GPG_KEY_ID --git-author-name \"semantic-release-bot\" --git-author-email \"shukomango@gmail.com\" gopkg-flow --source=. --dry-run=false --token=env://GITHUB_TOKEN"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

